Bump SDL dependency to latest
allyourcodebase/SDL main has a fix for this build error:

```
      └─ compile lib SDL3_image debug native
         └─ compile lib SDL3 debug native
            └─ configure cmake header dependency to SDL_build_config.h failure
error: zig-pkg/N-V-__8AABHq9wIiTHGY4qR6mw45F_TX8FSvqsQQ-Wtq1tzY/include/build_config/SDL_build_config.h.cmake: config header value unused: HAVE_CALLOC
error: zig-pkg/N-V-__8AABHq9wIiTHGY4qR6mw45F_TX8FSvqsQQ-Wtq1tzY/include/build_config/SDL_build_config.h.cmake: config header value unused: HAVE_REALLOC
error: zig-pkg/N-V-__8AABHq9wIiTHGY4qR6mw45F_TX8FSvqsQQ-Wtq1tzY/include/build_config/SDL_build_config.h.cmake: config header value unused: HAVE_FREE
error: zig-pkg/N-V-__8AABHq9wIiTHGY4qR6mw45F_TX8FSvqsQQ-Wtq1tzY/include/build_config/SDL_build_config.h.cmake: config header value unused: HAVE_MPROTECT
error: zig-pkg/N-V-__8AABHq9wIiTHGY4qR6mw45F_TX8FSvqsQQ-Wtq1tzY/include/build_config/SDL_build_config.h.cmake: config header value unused: HAVE_SYSCTL
```

We have to pick up the latest SDL, otherwise we transitively depend on a
code prior to the fix.